services:
  postgres-server:
    image: postgres:16.2
    container_name: postgres-server
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dbmigrationservice:
    image: dbmigrationservice
    build:
      context: .
      dockerfile: DbMigrationService/Dockerfile
    environment:
      - CONNECTION_STRING
    depends_on:
      - postgres-server

  apiservice:
    image: apiservice
    build:
      context: .
      dockerfile: ApiService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - CONNECTION_STRING
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - postgres-server

  worker:
    image: worker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - CONNECTION_STRING
    depends_on:
      - postgres-server

volumes:
  postgres-data:

