// <auto-generated />
using Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbMigrationService.Migrations
{
    [DbContext(typeof(GoldDbContext))]
    [Migration("20240706174231_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JO_70", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_70");
                });

            modelBuilder.Entity("JO_71", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_71");
                });

            modelBuilder.Entity("JO_72", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_72");
                });

            modelBuilder.Entity("JO_73", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_73");
                });

            modelBuilder.Entity("JO_74", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_74");
                });

            modelBuilder.Entity("JO_75", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_75");
                });

            modelBuilder.Entity("JO_76", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_76");
                });

            modelBuilder.Entity("JO_92224", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_92224");
                });

            modelBuilder.Entity("JO_92225", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_92225");
                });

            modelBuilder.Entity("JO_92226", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_92226");
                });

            modelBuilder.Entity("JO_92276", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_92276");
                });

            modelBuilder.Entity("JO_92277", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_92277");
                });

            modelBuilder.Entity("JO_92278", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_92278");
                });

            modelBuilder.Entity("JO_9751", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_9751");
                });

            modelBuilder.Entity("JO_9752", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_9752");
                });

            modelBuilder.Entity("JO_9753", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_9753");
                });

            modelBuilder.Entity("JO_9754", b =>
                {
                    b.Property<long>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Time"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<double>("Q1")
                        .HasColumnType("double precision");

                    b.Property<double>("Q10")
                        .HasColumnType("double precision");

                    b.Property<double>("Q11")
                        .HasColumnType("double precision");

                    b.Property<double>("Q12")
                        .HasColumnType("double precision");

                    b.Property<double>("Q13")
                        .HasColumnType("double precision");

                    b.Property<double>("Q14")
                        .HasColumnType("double precision");

                    b.Property<double>("Q15")
                        .HasColumnType("double precision");

                    b.Property<double>("Q16")
                        .HasColumnType("double precision");

                    b.Property<double>("Q17")
                        .HasColumnType("double precision");

                    b.Property<double>("Q18")
                        .HasColumnType("double precision");

                    b.Property<double>("Q19")
                        .HasColumnType("double precision");

                    b.Property<double>("Q193")
                        .HasColumnType("double precision");

                    b.Property<double>("Q2")
                        .HasColumnType("double precision");

                    b.Property<double>("Q20")
                        .HasColumnType("double precision");

                    b.Property<double>("Q21")
                        .HasColumnType("double precision");

                    b.Property<double>("Q22")
                        .HasColumnType("double precision");

                    b.Property<double>("Q23")
                        .HasColumnType("double precision");

                    b.Property<double>("Q24")
                        .HasColumnType("double precision");

                    b.Property<double>("Q3")
                        .HasColumnType("double precision");

                    b.Property<double>("Q4")
                        .HasColumnType("double precision");

                    b.Property<double>("Q5")
                        .HasColumnType("double precision");

                    b.Property<double>("Q6")
                        .HasColumnType("double precision");

                    b.Property<double>("Q60")
                        .HasColumnType("double precision");

                    b.Property<double>("Q61")
                        .HasColumnType("double precision");

                    b.Property<double>("Q62")
                        .HasColumnType("double precision");

                    b.Property<double>("Q63")
                        .HasColumnType("double precision");

                    b.Property<double>("Q64")
                        .HasColumnType("double precision");

                    b.Property<double>("Q7")
                        .HasColumnType("double precision");

                    b.Property<double>("Q70")
                        .HasColumnType("double precision");

                    b.Property<double>("Q8")
                        .HasColumnType("double precision");

                    b.Property<double>("Q80")
                        .HasColumnType("double precision");

                    b.Property<double>("Q9")
                        .HasColumnType("double precision");

                    b.Property<string>("ShowCode")
                        .HasColumnType("text");

                    b.Property<string>("ShowName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Time");

                    b.ToTable("JO_9754");
                });
#pragma warning restore 612, 618
        }
    }
}
